[shell]
program = "tmux"

[font]
size = 12

[font.normal]
family = "FiraCodeNerdFont"

[window]
title = "Terminal"

[window.padding]
x = 12
y = 12

[[keyboard.bindings]]
chars = "printf \"\\033c\"\n"
key = "L"
mods = "Control"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = '0x151515'
foreground = '0xd8d8d8'

[colors.cursor]
text = '0x151515'
cursor = '0xd8d8d8'

[colors.normal]
black = '0x151515'
red = '0xab4642'
green = '0xa1b56c'
yellow = '0xf7ca88'
blue = '0x7cafc2'
magenta = '0xba8baf'
cyan = '0x86c1b9'
white = '0xd8d8d8'

[colors.bright]
black = '0x585858'
red = '0xdc9656'
green = '0x282828'
yellow = '0x383838'
blue = '0xb8b8b8'
magenta = '0xe8e8e8'
cyan = '0xa16946'
white = '0xf8f8f8'
