#!/bin/bash

cd "${0%/*}" || exit 0

create_symlink() {
  test -h $2 || ( rm -rf $2 && mkdir -p $( dirname $2 ) && ln -s $1 $2 )
}

create_dotfiles_symlink() {
  create_symlink ~/.dotfiles/$1 $2
}

create_dotfiles_symlink git/.gitconfig ~/.gitconfig

create_dotfiles_symlink git/ignore ~/.config/git/ignore

create_dotfiles_symlink bash/.bashrc ~/.bashrc

create_dotfiles_symlink bash/.bash_aliases ~/.bash_aliases

create_dotfiles_symlink bash/.profile ~/.profile

# create_dotfiles_symlink X/.Xdefaults ~/.Xdefaults

create_dotfiles_symlink doublecmd/doublecmd.xml ~/.config/doublecmd/doublecmd.xml

create_dotfiles_symlink doublecmd/shortcuts.scf ~/.config/doublecmd/shortcuts.scf

# create_dotfiles_symlink gtk/.gtkrc-2.0 ~/.gtkrc-2.0

create_dotfiles_symlink gtk/gtk-3.0 ~/.config/gtk-3.0

# create_dotfiles_symlink X/.inputrc ~/.inputrc

# create_dotfiles_symlink X/.screenrc ~/.screenrc

create_dotfiles_symlink alacritty/alacritty.toml ~/.config/alacritty/alacritty.toml

create_dotfiles_symlink tmux/.tmux.conf ~/.tmux.conf

create_dotfiles_symlink sway/config ~/.config/sway/config

create_dotfiles_symlink sway/config.d ~/.config/sway/config.d

create_dotfiles_symlink waybar ~/.config/waybar

# create_dotfiles_symlink nvim/init.vim ~/.config/nvim/init.vim

# create_dotfiles_symlink ruby/.gemrc ~/.gemrc

# create_dotfiles_symlink dunst/dunstrc ~/.config/dunst/dunstrc

create_dotfiles_symlink rofi ~/.config/rofi

(
  cd subl || exit 0

  for dir in Packages/User*; do
    create_dotfiles_symlink subl/$dir ~/.config/sublime-text/$dir
  done
)

# bash if dropbox executable exists
if which dropbox > /dev/null; then
  # Dropbox symlinks
  if [[ -d ~/Dropbox/ubuntu ]]; then
    create_symlink ~/Dropbox/ubuntu/fonts ~/.fonts
    create_symlink ~/Dropbox/ubuntu/various_configs/texmf ~/texmf
    create_symlink ~/Dropbox/ubuntu/ssh/config ~/.ssh/config
    create_symlink ~/Dropbox/ubuntu/ssh/known_hosts ~/.ssh/known_hosts
    create_symlink ~/Dropbox/Pictures/unsplash ~/Pictures/unsplash
    create_symlink ~/Dropbox/Pictures/unsplash_hd ~/Pictures/unsplash_hd
  fi
else
  echo "Dropbox not present - see setup/dropbox.md for setup instructions."
fi
