#!/usr/bin/env ruby
require 'optparse'
require 'whenever'

from = 1000
to = 1500
window = nil

OptionParser.new do |opts|
  opts.banner = 'Usage: press_keys [options] [keys to press]...'

  opts.on('--window o', '-w o', 'Window wmctrl string') { |o| window = o }
  opts.on('--from o', '-f o', 'Interval from [ms]') { |o| from = o.to_i }
  opts.on('--to o', '-t o', 'Interval to [ms]') { |o| to = o.to_i }
end.parse!

keys = ARGV

def rand_between(from, to)
  (rand(to - from) + from).to_f / 1000
end

def sleep_for(from, to)
  sleep rand_between(from, to)
end

loop do
  if `xdotool getactivewindow getwindowname`.chomp == window
    shuffled = keys.shuffle
    shuffled.each do |key|
      `xdotool key #{key}`
      sleep_for(30, 100)
    end
    puts shuffled.join(' - ')
  else
    puts '-----'
  end
  sleep_for(from, to)
end
