set $ico_lens 

bindsym $mod+slash exec $dotfiles_dir/bin/sway/sway_focus_pinned 'freelens' --workspace $ico_lens --app-id freelens
bindsym $mod+Shift+slash move container to workspace $ico_lens

assign [app_id="freelens"] → $ico_lens
