set $ico_mail 

bindsym $mod+5 exec $dotfiles_dir/bin/sway/sway_focus_pinned 'thunderbird' --workspace $ico_mail --app-id thunderbird_thunderbird

assign [app_id="thunderbird_thunderbird"] → $ico_mail

for_window [app_id="thunderbird" title="Write(.*)"] floating enable, border $floating_border
