set $ico_slack 

bindsym $mod+s exec $dotfiles_dir/bin/sway/sway_focus_pinned 'slack --ozone-platform-hint=auto' --workspace $ico_slack --app-id slack
bindsym $mod+Shift+s move container to workspace $ico_slack

assign [app_id="slack"] → $ico_slack
