set $ico_lock 

bindsym $mod+n exec $dotfiles_dir/bin/sway/sway_focus_pinned 'keepassxc' --workspace $ico_lock --app-id 'org.keepassxc.KeePassXC'
bindsym $mod+Shift+n move container to workspace $ico_lock

assign [app_id="org.keepassxc.KeePassXC"] → $ico_lock
