set $ico_music 

bindsym $mod+m exec $dotfiles_dir/bin/sway/sway_focus_pinned 'spotify --ozone-platform-hint=auto' --workspace $ico_music --window-class Spotify --app-id spotify
bindsym $mod+Shift+m move container to workspace $ico_music
bindsym Pause exec $dotfiles_dir/bin/spotify/play_pause
bindsym Shift+Pause exec $dotfiles_dir/bin/spotify/play_pause next
bindsym Control+Shift+Pause exec $dotfiles_dir/bin/spotify/play_pause prev

assign [app_id="spotify"] → $ico_music
assign [class="Spotify"] → $ico_music
