bindsym $mod+2 exec $dotfiles_dir/bin/sway/sway_focus_or_run 'subl --new-window' --app-id sublime_text --app-id foot-nvim --app-id cursor --window-class Code --app-id dev.zed.Zed --window-class Cursor

for_window [app_id="sublime_text" title="Open File"] floating enable, resize set width 50ppt height 50ppt, move position center
