set $ico_code 

bindsym $mod+z exec $dotfiles_dir/bin/sway/sway_focus_pinned 'while read url; do (google-chrome --new-window $url &); done < ~/.local/share/dotfiles-private/config/sway/data/code_urls.txt' --workspace $ico_code --window-class Google-chrome --app-id google-chrome --strict-workspace-check
bindsym $mod+Shift+z move container to workspace $ico_code
