set $ico_whatsapp 

bindsym $mod+w exec $dotfiles_dir/bin/sway/sway_focus_pinned 'while read url; do (google-chrome --app=$url &); done < ~/Dropbox/dotfiles/sway/whatsapp_urls.txt' --workspace $ico_whatsapp --window-class Google-chrome --app-id chrome-web.whatsapp.com__-Default
bindsym $mod+Shift+w move container to workspace $ico_whatsapp
