set $ico_calendar 

bindsym $mod+x exec $dotfiles_dir/bin/sway/sway_focus_pinned 'while read url; do (google-chrome --app=$url &); done < ~/.local/share/dotfiles-private/config/sway/data/calendar_urls.txt' --workspace $ico_calendar --window-class Google-chrome --app-id chrome-calendar.google.com__calendar-Default
bindsym $mod+Shift+x move container to workspace $ico_calendar
