set $ico_gimp 

bindsym $mod+g exec $dotfiles_dir/bin/sway/sway_focus_pinned 'gimp' --workspace $ico_gimp --window-class Gimp-2.10
bindsym $mod+Shift+g move container to workspace $ico_gimp

assign [app_id="gimp"] → $ico_gimp
