set $mod Mod4

set $left h
set $down j
set $up k
set $right l

set $base-blackey $base00
set $base-blue $base0D
set $base-brown $base0F
set $base-green $base0B
set $base-orange $base09
set $base-purple $base0E
set $base-red $base08
set $base-turqoise $base0C
set $base-whitey $base07
set $base-yellow $base0A

set $base-color-on-focus $base-focus-foreground

set $term foot

set $dotfiles_dir ~/.local/share/dotfiles

set $ico_game 

set $floating_border pixel 4
