assign [app_id="net.thunderbird.Thunderbird"] → $ico_mail

assign [app_id="doublecmd-qt"] → $ico_folder

assign [app_id="Slack"] → $ico_slack
assign [class="Slack"] → $ico_slack

assign [app_id="Freelens"] → $ico_lens

assign [app_id="com.spotify.Client"] → $ico_music

assign [app_id="org.gimp.GIMP"] → $ico_gimp

assign [app_id="org.keepassxc.KeePassXC"] → $ico_lock
