exec /usr/libexec/lxqt-policykit-agent

exec_always {
  dunst
}

exec_always {
  swaymsg input "type:keyboard" xkb_switch_layout 0
}

exec_always {
  ~/.local/share/dotfiles/bin/sway/sway_select_display --handle-reload
}
