#!/usr/bin/env python3
import subprocess
import re

acpi = subprocess.check_output('acpi', shell=True).strip().decode('utf-8')
if acpi is '':
    exit(0)

is_charging = re.search('Charging|Full', acpi)
percentage = re.search(',\s([^%]+)%', acpi).group(1)

icon = ''
output = icon + '  '
output += percentage

print(output)
if is_charging:
    color = '#90a959'
    print()
    print(color)
elif int(percentage) <= 25:
    color = '#ac4142'
    print()
    print(color)
