#!/home/petr/.rbenv/shims/ruby
memory = `cat /proc/meminfo`.chomp

output = [
  ['MemAvailable'],
  # ['SwapFree', 'SwapTotal']
].map do |keys|
  free = memory[/#{keys[0]}.+\n/][/\d+/].to_i
  max = memory[/#{keys[1]}.+\n/][/\d+/].to_i
  used = 100*(1-free/max.to_f)
  "#{used.round}%"
end

puts " #{output.join('')}"
