#!/home/petr/.rvm/rubies/default/bin/ruby
show_gpu = false
output = []
sensors = `sensors`.chomp
output << sensors[/ISA adapter\n.+(\d+\.\d+)/][/\d+\.\d+/].to_f.round
if show_gpu
  begin
    output << sensors[/PCI adapter\n.+(\d+\.\d+)/][/\d+\.\d+/].to_f.round
  rescue
  end
end
output.map! { |s| "#{s}°" }
puts "  #{output.join(' ')}"
