#!/home/petr/.rbenv/shims/ruby
require 'json'
sensors = JSON.parse(`sensors -j`.chomp)

if sensors["acpitz-acpi-0"] && sensors["acpitz-acpi-0"]["temp1"] && sensors["acpitz-acpi-0"]["temp1"]["temp1_input"]
  puts "  #{sensors["acpitz-acpi-0"]["temp1"]["temp1_input"].round}°"
end
