#!/bin/bash
percent=$( amixer -D pulse sget Master | grep '\[on\]' | head -n1 | grep -o '[1-9][0-9]*%' )

if [[ $percent ]]; then
  icon=''
else
  icon=' '
  percent='OFF'
  color='#505050'
fi

echo "$icon $percent"

if [[ $color ]]; then
  echo
  echo "$color"
fi

handleButtons() {
  case $BLOCK_BUTTON in
    4 )
      amixer -D pulse sset Master 2%+ unmute; pkill -SIGRTMIN+10 i3blocks ;;
    5 )
      amixer -D pulse sset Master 2%- unmute; pkill -SIGRTMIN+10 i3blocks ;;
    1|3 )
      amixer -D pulse set Master 1+ toggle; pkill -SIGRTMIN+10 i3blocks ;;
  esac
}
handleButtons > /dev/null
