#!/bin/bash
listFile=~/.dotfiles/apt/ppa_list.txt

echoRed() {
	echo -e "\e[31m$@\e[0m"
}
echoGreen() {
	echo -e "\e[32m$@\e[0m"
}
echoYellow() {
	echo -e "\e[33m$@\e[0m"
}
notSudo() {
	[[ ! $( id -u ) = 0 ]]
}

if notSudo; then
  echoRed 'You need to run this script with sudo.'
  exit
fi
if [[ ! -f $listFile ]]; then
  echoRed "List of ppa not found in $listFile."
  exit
fi

while read line; do
  if [[ $( grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/* | grep $line ) ]]; then
    echoYellow "Skipping ppa \"$line\" - already in sources. "
  else
    echoGreen "Installing listed ppa \"$line\"."
    yes | add-apt-repository ppa:$line
  fi
done < $listFile
