#!/bin/bash
echo "Installing n."
if which n > /dev/null; then
  echo "n is already installed."
else
  curl -L http://git.io/n-install | bash
fi

echo "Installing rvm."
if which rvm > /dev/null; then
  echo "rvm is already installed."
else
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  \curl -sSL https://get.rvm.io | bash -s stable
fi

