#!/bin/bash
listFile=~/.dotfiles/apt/packages_list.txt

echoRed() {
	echo -e "\e[31m$@\e[0m"
}
echoGreen() {
	echo -e "\e[32m$@\e[0m"
}
echoYellow() {
	echo -e "\e[33m$@\e[0m"
}
notSudo() {
	[[ ! $( id -u ) = 0 ]]
}

if notSudo; then
  echoRed 'You need to run this script with sudo.'
  exit
fi
if [[ ! -f $listFile ]]; then
  echoRed "List of packages not found in $listFile."
  exit
fi

apt-get install $( echo $( cat $listFile ) )
