#!/bin/bash
state=$( xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-ac )

if [ "$state" -eq 0 ]; then
  # is set to do nothing
  fg=0081F2
else
  # is set to suspend
  fg=03a904
fi

echo "<txt><span foreground=\"#$fg\">S</span></txt>"
