#!/bin/bash
percent=$( awk 'NR==3 {print $3}' /proc/net/wireless | awk -F'.' '{ print $1 }' )

if [[ $percent -le 30 ]]; then
  # red
  fg=fd4343
elif [[ $percent -le 75 ]]; then
  # grey
  fg=767f7f
else
  # green
  fg=03a904
fi

if [[ $percent ]]; then
  echo "<txt><span foreground=\"#$fg\">$percent%</span></txt>"
else
  echo "<txt><span foreground=\"#ac2727\">DC</span></txt>"
fi
