[shell]
program = "ssh-add"

[font]
size = 14

[font.normal]
family = "FiraCodeNerdFontMono"

[window]
title = "sway-ssh-askpass"

[window.padding]
x = 48
y = 48

[colors.primary]
background = '0xab4642'
foreground = '0x151515'
